services:
  app:
    build:
      context: ./
      target: runner
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: yuser
      POSTGRES_PASSWORD: H@ck3rNews
      POSTGRES_DATABASE: ynews
      POSTGRES_HOST: localhost
