services:
  app:
    build:
      context: ./
      target: runner
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: yuser
      POSTGRES_PASSWORD: H@ck3rNews
      POSTGRES_DB: ynews
      POSTGRES_HOST: postgres

  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    restart: always
    environment:
      POSTGRES_USER: yuser
      POSTGRES_PASSWORD: H@ck3rNews
      POSTGRES_DB: ynews
      PGDATA: /var/lib/postgresql/ynews/
    volumes:
      - dbynews:/var/lib/postgresql/ynews/
    ports:
      - 6543:5432

volumes:
  dbynews:

