
import './globals.css'
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Hello World',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-orange-200'>
        {children}
      </body>
    </html>
  )
}
