
import './globals.css'
import { Metadata } from "next";
import NavBar from "@/components/NavBar";
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Hello World',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex justify-center text-center mt-2'>
        <div className='w-11/12 bg-orange-50' >
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
